"""Initial migration

Revision ID: ce373139ec0b
Revises: 
Create Date: 2025-11-09 20:44:02.025155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce373139ec0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('disorder', sa.String(length=50), nullable=False),
    sa.Column('disorder_full', sa.String(length=200), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('last_visit', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ehr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('diagnosis_date', sa.String(length=50), nullable=True),
    sa.Column('comorbidities', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('last_lab_work', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('mood', sa.Float(), nullable=True),
    sa.Column('sleep', sa.Float(), nullable=True),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wearables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('last_sync', sa.String(length=50), nullable=True),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True),
    sa.Column('heart_rate_resting', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('steps_avg', sa.Integer(), nullable=True),
    sa.Column('steps_goal', sa.Integer(), nullable=True),
    sa.Column('sleep_avg', sa.Float(), nullable=True),
    sa.Column('sleep_goal', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.String(length=50), nullable=True),
    sa.Column('hrv_avg', sa.Integer(), nullable=True),
    sa.Column('hrv_baseline', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wearables')
    op.drop_table('trend_data')
    op.drop_table('timeline_events')
    op.drop_table('ehr')
    op.drop_table('patients')
    # ### end Alembic commands ###
